networks:
  local:
    driver: bridge

volumes:
  mariadb-data:

services:
  backend:
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - '8080:80'
    volumes:
      - ./src:/var/www/html/:rw
    networks:
      - local

  db:
    image: mariadb:10.6.7
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASS}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASS}
    ports:
      - '8082:3306'
    volumes:
      - mariadb-data:/var/lib/mysql:rw
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql:r
    networks:
      - local

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - '8081:80'
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=${DB_PASS}
    networks:
      - local
    depends_on:
      - db
