networks:
  local:
    driver: bridge

volumes:
  mariadb-data:

services:
  backend:
    image: php:8.1-apache
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    networks:
      - local
    depends_on:
      - db

  db:
    image: mariadb:10.6.7
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_USER: username
      MARIADB_PASSWORD: password
    ports:
      - "8082:3306"
    volumes:
      - mariadb-data:/var/lib/mysql:rw
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql:r
    networks:
      - local

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=password
    networks:
      - local
    depends_on:
      - db
